[package]
name = "socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdtp = {path = "../sdtp"}
tokio = { version = "1.15.0", features = ["net", "macros", "rt", "fs", "sync", "time"] }